### ISSUE TITLE
Exception when clicking "temperature data by month" after searching a destination. 

### ISSUE THREAD

**Issue by btormino** [STL-WomenPlus-Mar22-LiftOff/bucket-list-adventures#39]
After searching for a destination, an exception is thrown in the ApplicationRepository file. *See pic
![Exception for weather data](https://user-images.githubusercontent.com/102358436/215287922-c1088a9f-5e8a-433e-88a2-ca58cbda42d0.png)

**Comment by brigid-book** [comment]
This is because you don't have the weather station data in your table. I've [posted about it in slack](https://launchcodewom-alr4793.slack.com/archives/C04EECLADFD/p1674682800979469) along with the csv file containing the data . Since each of us has our own separate mysql server, each person will need to add the data to the database on their own computer. This can be done by right-clicking the "weatherstations" table and selecting "Table Data Import Wizard".
